### ISSUE TITLE
Team Synchronization options is unavailable when using SVNKIT

### ISSUE THREAD

**Issue by jeffreynelson** [subclipse/subclipse#67] opened 2018-05-21 15:54 UTC
If we switch to JAVAHL then it works after you delete and re-checkout all of your projects from SVN.

IDE: JBoss Developer Studio V11.2.0 and V11.3.0.
Eclipse Version: 4.7.3.v20180330-0640

**Installed Plugins:**
Subclipse 4.2.4.201804261743 org.tigris.subversion.subclipse.feature.group Subclipse
Subclipse Integration for Mylyn (Optional) 4.2.0.1 org.tigris.subversion.subclipse.mylyn.feature.feature.group Subclipse
Subversion JavaHL Windows Native DLL's 1.9.7.201803201521 org.tigris.subversion.clientadapter.javahl.feature.feature.group Subclipse
Subversion Revision Graph 4.2.0.1 org.tigris.subversion.subclipse.graph.feature.feature.group Subclipse
SVNKit Client Adapter 1.8.12.1 org.tigris.subversion.clientadapter.svnkit.feature.feature.group Subclipse
SVNKit Library 1.8.15.r10636 org.tmatesoft.svnkit.feature.group TMate Software

**Comment by jeffreynelson** [comment] 2018-05-22 13:21
If the JavaHL is required and SVNKIT does not work on windows then can you change the default SVN library under teams --> SVN to JAVAHL?

**Comment by markphip** [comment] 2018-05-22 13:26
There are no options in the product that are predicated on using one adapter or the other.  There can be bugs or slight differences in behavior in one API implementation or the other, but both provide all of the API's we use.  JavaHL is already the default implementation provided that it has been installed and is available.

So obviously you had some kind of problem here, but your diagnosis of the causes was not correct.  I do generally recommend you use JavaHL if possible, since that is the API implementation that comes from Subversion itself so is going to be most compatible with the SVN command line and other clients you might be using.  That said, SVNKit generally offers very good compatibility as well.

I am closing this just because I do not see that there is anything here that can be acted upon.

**Closed by markphip** 2018-05-22 13:26 UTC

**Comment by jeffreynelson** [comment] 2018-05-22 13:32
Thank You,

However, when using the SVNKit adapter the team sync options is greyed out.
