### ISSUE TITLE
Eclipse 2020-03 fails to startup after last update - May 04 2020

### ISSUE THREAD

**Issue by maurorulli** [subclipse/subclipse#132] opened 2020-05-04 07:16 UTC
Eclipse crashes every time after 2-3 seconds form main window appear.
ErrPid log:
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.lang.ClassLoader$NativeLibrary.load(Ljava/lang/String;Z)V+0
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+328
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+148
j  java.lang.Runtime.loadLibrary0(Ljava/lang/Class;Ljava/lang/String;)V+54
j  java.lang.System.loadLibrary(Ljava/lang/String;)V+7
j  org.tigris.subversion.svnclientadapter.javahl.JhlClientAdapterFactory.isAvailable()Z+150
j  org.tigris.subversion.clientadapter.javahl.Activator.isAvailable()Z+0
j  org.tigris.subversion.clientadapter.Activator.getClientAdapter(Ljava/lang/String;)Lorg/tigris/subversion/svnclientadapter/ISVNClientAdapter;+46
j  org.tigris.subversion.subclipse.core.SVNClientManager.getAdapter(Ljava/lang/String;)Lorg/tigris/subversion/svnclientadapter/ISVNClientAdapter;+48
j  org.tigris.subversion.subclipse.core.SVNClientManager.getSVNClient()Lorg/tigris/subversion/svnclientadapter/ISVNClientAdapter;+5
j  org.tigris.subversion.subclipse.core.SVNProviderPlugin.getSVNClient()Lorg/tigris/subversion/svnclientadapter/ISVNClientAdapter;+4
j  org.tigris.subversion.subclipse.core.status.NonRecursiveStatusUpdateStrategy.statusesToUpdate(Lorg/eclipse/core/resources/IResource;)[Lorg/tigris/subversion/svnclientadapter/ISVNStatus;+60
j  org.tigris.subversion.subclipse.core.status.StatusCacheManager.refreshStatus(Lorg/eclipse/core/resources/IResource;Z)[Lorg/eclipse/core/resources/IResource;+59
j  org.tigris.subversion.subclipse.core.resourcesListeners.FileModificationManager.refreshStatus([Lorg/eclipse/core/resources/IResource;)V+55
j  org.tigris.subversion.subclipse.core.resourcesListeners.FileModificationManager.access$2(Lorg/tigris/subversion/subclipse/core/resourcesListeners/FileModificationManager;[Lorg/eclipse/core/resources/IResource;)V+2
j  org.tigris.subversion.subclipse.core.resourcesListeners.FileModificationManager$2.run()V+42
j  org.tigris.subversion.subclipse.core.util.JobUtility$1$1.run(Lorg/eclipse/core/runtime/IProgressMonitor;)V+4
j  org.eclipse.core.internal.resources.Workspace.run(Lorg/eclipse/core/runtime/ICoreRunnable;Lorg/eclipse/core/runtime/jobs/ISchedulingRule;ILorg/eclipse/core/runtime/IProgressMonitor;)V+69
j  org.eclipse.core.internal.resources.Workspace.run(Lorg/eclipse/core/resources/IWorkspaceRunnable;Lorg/eclipse/core/runtime/jobs/ISchedulingRule;ILorg/eclipse/core/runtime/IProgressMonitor;)V+6
j  org.tigris.subversion.subclipse.core.util.JobUtility$1.run(Lorg/eclipse/core/runtime/IProgressMonitor;)Lorg/eclipse/core/runtime/IStatus;+21
j  org.eclipse.core.internal.jobs.Worker.run()V+33
v  ~StubRoutines::call_stub

Please I need a fix to work!

**Comment by markphip** [comment] 2020-05-04 10:53
Duplicate of #131 

If you still have the error log files like the ones posted in that issue it would be nice to have a set of them from another machine so I can look for similarities that might point to a cause.

**Closed by markphip** 2020-05-04 10:53 UTC
